const APIKEY = process.env.REACT_APP_APIKEY;
const AUTHDOMAIN = process.env.REACT_APP_AUTHDOMAIN;
const PROJECTID = process.env.REACT_APP_PROJECTID;
const STORAGEBUCKET = process.env.REACT_APP_STORAGEBUCKET;
const MESSAGINGSENDERID = process.env.REACT_APP_MESSAGINGSENDERID;
const APPID = process.env.REACT_APP_APPID;

export { APIKEY, AUTHDOMAIN, PROJECTID, STORAGEBUCKET, MESSAGINGSENDERID, APPID };
